# SPDX-License-Identifier: MulanPSL-2.0
"""soma_d1 — Soma (body model) provider for the Beingbeyond D1.

Serves the three robonix/system/soma contracts over gRPC so downstream
consumers (scene, navigation, collision monitors) can learn what this
robot is:

  robonix/system/soma/description        → D1 URDF + metadata
  robonix/system/soma/footprint          → 2D base footprint in base frame
  robonix/system/soma/sensor_extrinsics  → static sensor mounts

The D1 is a FIXED-BASE arm (revolute joints only, no wheel/continuous
joints, no chassis primitive) — so this body model has a small static
base footprint and no mobile base. A navigation consumer that inspects
soma can reject "move to X" on embodied grounds.

Mirrors the voiceprint_service gRPC pattern: subclass each codegen
Servicer, attach via Service.attach_grpc_servicer, run via Service.run.
"""
from __future__ import annotations

import logging
import math
import os

from robonix_api import Service, Ok, Err

# codegen products (generated by `rbnx codegen` into rbnx-build/codegen/proto_gen,
# put on PYTHONPATH by scripts/start.sh). Names follow the contract/IDL mapping:
#   contract robonix/system/soma/<x>  → RobonixSystemSoma<X>Servicer
#   soma/srv/GetDescription.srv       → soma_pb2.GetDescription_{Request,Response}
#   soma/msg/SensorExtrinsic.msg      → soma_pb2.SensorExtrinsic
#   geometry_msgs/Point,Transform     → geometry_msgs_pb2.{Point,Transform}
import robonix_contracts_pb2_grpc as pb_grpc  # type: ignore[import-not-found]
import soma_pb2 as soma  # type: ignore[import-not-found]
import geometry_msgs_pb2 as geo  # type: ignore[import-not-found]

log = logging.getLogger("soma_d1")

# ── Body model (populated in on_init) ───────────────────────────────────────
_urdf_xml: str = ""
_model_name: str = "beingbeyond_d1"
_base_frame: str = "link_base"
_mass_kg: float = -1.0
_footprint_pts: list[tuple[float, float]] = []
_sensors: list[dict] = []


def _default_footprint() -> list[tuple[float, float]]:
    """A small square base footprint (m) in base_frame — the arm's mount,
    CCW, z=0. D1 has no mobile base; this is just its static base hull."""
    h = 0.10  # half-side, 0.20 m square
    return [(h, h), (-h, h), (-h, -h), (h, -h)]


soma_svc = Service(id="soma", namespace="robonix/system/soma")


# ── gRPC servicers ───────────────────────────────────────────────────────────


class _DescriptionServicer(pb_grpc.RobonixSystemSomaDescriptionServicer):
    def GetDescription(self, request, context):  # noqa: N802 (gRPC method)
        return soma.GetDescription_Response(
            urdf_xml=_urdf_xml,
            model_name=_model_name,
            mass_kg=_mass_kg,
            base_frame=_base_frame,
        )


class _FootprintServicer(pb_grpc.RobonixSystemSomaFootprintServicer):
    def GetFootprint(self, request, context):  # noqa: N802
        pts = [geo.Point(x=float(x), y=float(y), z=0.0) for x, y in _footprint_pts]
        # inscribed = largest disc inside an axis-aligned box → min |x|,|y|;
        # circumscribed = smallest disc enclosing → max vertex radius.
        inscribed = min([min(abs(x), abs(y)) for x, y in _footprint_pts],
                        default=0.0)
        circumscribed = max([math.hypot(x, y) for x, y in _footprint_pts],
                            default=0.0)
        return soma.GetFootprint_Response(
            points=pts,
            base_frame=_base_frame,
            inscribed_radius_m=float(inscribed),
            circumscribed_radius_m=float(circumscribed),
        )


class _SensorExtrinsicsServicer(pb_grpc.RobonixSystemSomaSensorExtrinsicsServicer):
    def GetSensorExtrinsics(self, request, context):  # noqa: N802
        kind = getattr(request, "sensor_kind", "") or ""
        out = []
        for s in _sensors:
            if kind and s.get("kind", "") != kind:
                continue
            t = s.get("transform", {})
            tr = geo.Transform()
            tr.translation.x = float(t.get("x", 0.0))
            tr.translation.y = float(t.get("y", 0.0))
            tr.translation.z = float(t.get("z", 0.0))
            tr.rotation.x = float(t.get("qx", 0.0))
            tr.rotation.y = float(t.get("qy", 0.0))
            tr.rotation.z = float(t.get("qz", 0.0))
            tr.rotation.w = float(t.get("qw", 1.0))
            out.append(soma.SensorExtrinsic(
                sensor_name=s.get("sensor_name", ""),
                parent_frame=s.get("parent_frame", _base_frame),
                child_frame=s.get("child_frame", ""),
                transform=tr,
            ))
        return soma.GetSensorExtrinsics_Response(sensors=out)


soma_svc.attach_grpc_servicer(
    "robonix/system/soma/description", _DescriptionServicer(),
)
soma_svc.attach_grpc_servicer(
    "robonix/system/soma/footprint", _FootprintServicer(),
)
soma_svc.attach_grpc_servicer(
    "robonix/system/soma/sensor_extrinsics", _SensorExtrinsicsServicer(),
)


# ── lifecycle ────────────────────────────────────────────────────────────────


@soma_svc.on_init
def init(cfg: dict):
    """Load the D1 URDF + body metadata once. All fields are config-
    overridable; the URDF defaults to the SDK's bundled D1 model."""
    global _urdf_xml, _model_name, _base_frame, _mass_kg
    global _footprint_pts, _sensors
    try:
        urdf_path = cfg.get("urdf_path", "")
        if not urdf_path:
            from beingbeyond_d1_sdk.urdf_path import get_default_urdf_path
            urdf_path = get_default_urdf_path()
        if not os.path.isfile(urdf_path):
            return Err(f"URDF not found: {urdf_path}")
        with open(urdf_path, "r", encoding="utf-8") as f:
            _urdf_xml = f.read()

        _model_name = cfg.get("model_name", "beingbeyond_d1")
        _base_frame = cfg.get("base_frame", "link_base")
        _mass_kg = float(cfg.get("mass_kg", -1.0))

        pts = cfg.get("footprint_xy_pts")
        _footprint_pts = ([(float(p[0]), float(p[1])) for p in pts]
                          if pts else _default_footprint())
        # Optional static sensor mounts; default none (the grasp skill owns
        # its own hand-eye calibration for now).
        _sensors = cfg.get("sensors", []) or []

        log.info("soma_d1 init: model=%s base=%s urdf=%s footprint_pts=%d sensors=%d",
                 _model_name, _base_frame, urdf_path,
                 len(_footprint_pts), len(_sensors))
        return Ok()
    except Exception as exc:  # noqa: BLE001
        log.exception("soma_d1 init failed")
        return Err(f"soma_d1 init failed: {exc}")


def main() -> int:
    soma_svc.run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
